services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - telemedicine-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # Backend service
  backend:
    image: ${DOCKERHUB_USERNAME}/telemedicine-backend:${VERSION:-latest}
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/telemedicine
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - telemedicine-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  # Frontend service
  frontend:
    image: ${DOCKERHUB_USERNAME}/telemedicine-frontend:${VERSION:-latest}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - telemedicine-network
    stdin_open: true

networks:
  telemedicine-network:

volumes:
  mongodb_data: